version: "3.5"

services:

    app:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: app_blog
        container_name: app_blog
        env_file:
            - ./production.env
        volumes:
            - ./blog:/app/blog

        ports:
            - 5000:5000
        command: bash -c "
            ./wait-for-postgres.sh pg
            && python -m flask db upgrade
            && gunicorn --workers 2 --bind 0.0.0.0:5000 wsgi:app"
        depends_on:
            - pg

    pg:
        image: postgres:15.1
        container_name: postgres_blog
        env_file:
            - ./production.env
        volumes:
            - ./var/postgresql/data-prod:/var/lib/postgresql/data
        
        expose:
            - 5432:5432