"""add author model

Revision ID: 8fd13153c234
Revises: bd5c7653cdac
Create Date: 2023-01-17 22:49:57.706299

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8fd13153c234"
down_revision = "bd5c7653cdac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "author",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name=op.f("fk_author_user_id_user")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_author")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("author")
    # ### end Alembic commands ###
