"""add MTM in  model

Revision ID: 930215f7fd49
Revises: 12e6bfeba482
Create Date: 2023-01-21 02:37:20.962074

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "930215f7fd49"
down_revision = "12e6bfeba482"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tag",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=32), server_default="", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tag")),
    )
    op.create_table(
        "article_tag_association",
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"], ["article.id"], name=op.f("fk_article_tag_association_article_id_article")
        ),
        sa.ForeignKeyConstraint(["tag_id"], ["tag.id"], name=op.f("fk_article_tag_association_tag_id_tag")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("article_tag_association")
    op.drop_table("tag")
    # ### end Alembic commands ###
